version: '3'


services:
  app:
    build:
      context: .
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py import_clients_from_csv dataset.txt &&
             python manage.py runserver 0.0.0.0:8000"
        volumes:
          - ./:/app
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_DB=app
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=AcjkZtLdgiEh1f46QAqJcNjmShWAD9np
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=AcjkZtLdgiEh1f46QAqJcNjmShWAD9np
    ports:
      - "5433:5432"
